[build-system]
name = "fastai_classifier"
version = "0.0.1"
dependencies = [
    "fastbook==0.0.10",
    'importlib-metadata; python_version=>"3.7"',
    'importlib-metadata; python_version=<"3.8"'
]
